#!/bin/bash
for node in `cat nodelist`
do
echo "--------"$node"--------"
#ssh $node "date" > /dev/null 2>&1 
ssh $node "date;ls"  
echo done!
done





or

#!/bin/bash
for node in `cat nodelist`
do
echo $node
ssh $node  > /dev/null 2>&1 << eeooff
cd /home/asc16
hostname >>/home/asc16/zjhua/log
date >>/home/asc16/zjhua/log
exit
eeooff
echo done!
done





 nodelist include node name
 like:
 cu01
 cu02
